import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

type HeaderChoice = {
  key: string;
  kind: "host" | "suffix";
};

type HeaderMode = {
  id: "ascii" | "ascii-fragment" | "cjk" | "cjk-fragment";
  base: number;
  best: {
    tier1LeadStates: number;
    tier2LeadStates: number;
    tier3LeadStates: number;
    unusedLeadStates: number;
    tier1: HeaderChoice[];
    tier2: HeaderChoice[];
    tier3: HeaderChoice[];
  };
};

type HeaderReport = {
  structuralStates: number;
  genericLeadStates: number;
  modes: HeaderMode[];
};

type SymbolReport = {
  dictionaryTerms: Array<{ key: string }>;
  literalCharacters: Array<{ key: string }>;
};

type TokenizerModel = {
  schemaVersion: number;
  payloadTerms: string[];
  symbolCodeLengths?: Partial<Record<HeaderMode["id"], number[]>>;
  hostRoutes: Record<string, Array<{
    value: string;
    suffix?: { alphabet: "base64url" | "decimal" | "hex" | "lower-hyphen"; length: number };
  }>>;
};

const root = resolve(import.meta.dirname, "..");
const reportLabel = process.argv[2] ?? "data/training/full-2026-08-16/reports";
const reportDirectory = resolve(root, reportLabel);
const output = resolve(root, process.argv[3] ?? "src/generated/v2-codec-model.ts");
const payloadTermCount = 44;

const headers = JSON.parse(await readFile(resolve(reportDirectory, "header-shortlists.json"), "utf8")) as HeaderReport;
const symbols = JSON.parse(await readFile(resolve(reportDirectory, "common-symbols.json"), "utf8")) as SymbolReport;
const tokenizerPath = resolve(reportDirectory, "tokenizer-model.json");
const tokenizer = await readFile(tokenizerPath, "utf8")
  .then((value) => JSON.parse(value) as TokenizerModel)
  .catch(() => undefined);

if (headers.structuralStates !== 16 || headers.genericLeadStates !== 1) {
  throw new Error("The runtime v2 header requires 16 structural states and one generic lead");
}

const canonical = {
  schemaVersion: 3,
  structuralStates: headers.structuralStates,
  genericLeadStates: headers.genericLeadStates,
  modes: headers.modes.map((mode) => ({
    id: mode.id,
    base: mode.base,
    tier1LeadStates: mode.best.tier1LeadStates,
    tier2LeadStates: mode.best.tier2LeadStates,
    tier3LeadStates: mode.best.tier3LeadStates,
    unusedLeadStates: mode.best.unusedLeadStates,
    tier1: canonicalTier1(mode.best.tier1).map(encodeEntry),
    tier2: mode.best.tier2.map(encodeEntry),
    tier3: mode.best.tier3.map(encodeEntry),
  })),
  payloadTerms: tokenizer?.payloadTerms
    ?? symbols.dictionaryTerms.slice(0, payloadTermCount).map((entry) => entry.key),
  literalPriority: symbols.literalCharacters.map((entry) => entry.key).filter((value) => [...value].length === 1),
  hostRoutes: Object.fromEntries(Object.entries(tokenizer?.hostRoutes ?? {}).map(([host, routes]) => [
    host,
    routes.map((route) => ({
      value: route.value,
      ...(route.suffix ? { suffix: { alphabet: route.suffix.alphabet, length: route.suffix.length } } : {}),
    })),
  ])),
  symbolCodeLengths: Object.fromEntries(headers.modes.map((mode) => {
    const lengths = tokenizer?.symbolCodeLengths?.[mode.id] ?? Array.from({ length: 64 }, () => 6);
    if (lengths.length !== 64 || lengths.some((length) => !Number.isInteger(length) || length < 1 || length > 12)) {
      throw new Error(`Invalid ${mode.id} v2 Huffman code lengths`);
    }
    return [mode.id, lengths];
  })),
};
const contentHash = createHash("sha256").update(JSON.stringify(canonical)).digest("hex");

const arrays = new Map<string, string>();
const declarations: string[] = [];
function intern(entries: string[]): string {
  const serialized = JSON.stringify(entries);
  const existing = arrays.get(serialized);
  if (existing) return existing;
  const name = `entries${arrays.size}`;
  arrays.set(serialized, name);
  declarations.push(`const ${name}: readonly GeneratedHeaderEntry[] = ${serialized};`);
  return name;
}

const modeRows = canonical.modes.map((mode) => {
  const tier1 = intern(mode.tier1);
  const tier2 = intern(mode.tier2);
  const tier3 = intern(mode.tier3);
  return `  ${JSON.stringify(mode.id)}: {
    id: ${JSON.stringify(mode.id)},
    base: ${mode.base},
    tier1LeadStates: ${mode.tier1LeadStates},
    tier2LeadStates: ${mode.tier2LeadStates},
    tier3LeadStates: ${mode.tier3LeadStates},
    unusedLeadStates: ${mode.unusedLeadStates},
    tier1: ${tier1},
    tier2: ${tier2},
    tier3: ${tier3},
  }`;
});

const source = `// Generated by scripts/generate-v2-codec-model.ts.
// Source: ${reportLabel.replaceAll("\\", "/")}
// Reordering any entry changes the v2 wire format.

export type V2HeaderModeId = "ascii" | "ascii-fragment" | "cjk" | "cjk-fragment";
export type GeneratedHeaderEntry = \`h:\${string}\` | \`s:\${string}\`;
export type V2RouteAlphabet = "base64url" | "decimal" | "hex" | "lower-hyphen";
export type V2HostRoute = {
  readonly value: string;
  readonly suffix?: { readonly alphabet: V2RouteAlphabet; readonly length: number };
};

export type GeneratedHeaderTable = {
  readonly id: V2HeaderModeId;
  readonly base: number;
  readonly tier1LeadStates: number;
  readonly tier2LeadStates: number;
  readonly tier3LeadStates: number;
  readonly unusedLeadStates: number;
  readonly tier1: readonly GeneratedHeaderEntry[];
  readonly tier2: readonly GeneratedHeaderEntry[];
  readonly tier3: readonly GeneratedHeaderEntry[];
};

export const V2_CODEC_MODEL_SCHEMA = 3;
export const V2_CODEC_MODEL_HASH = ${JSON.stringify(contentHash)};
export const V2_STRUCTURAL_STATES = 16;
export const V2_GENERIC_LEAD_STATES = 1;

${declarations.join("\n")}

export const V2_HEADER_TABLES: Readonly<Record<V2HeaderModeId, GeneratedHeaderTable>> = {
${modeRows.join(",\n")},
};

export const V2_PAYLOAD_DICTIONARY: readonly string[] = ${JSON.stringify(canonical.payloadTerms)};
export const V2_PRIMARY_DICTIONARY: readonly string[] = ${JSON.stringify(canonical.payloadTerms.slice(0, 10))};
export const V2_EXTENDED_DICTIONARY: readonly string[] = ${JSON.stringify(canonical.payloadTerms.slice(10))};
export const V2_LITERAL_PRIORITY: readonly string[] = ${JSON.stringify(canonical.literalPriority)};
export const V2_HOST_ROUTE_TABLES: Readonly<Record<string, readonly V2HostRoute[]>> = ${JSON.stringify(canonical.hostRoutes)};
export const V2_SYMBOL_CODE_LENGTHS: Readonly<Record<V2HeaderModeId, readonly number[]>> = ${JSON.stringify(canonical.symbolCodeLengths)};
`;

await mkdir(dirname(output), { recursive: true });
await writeFile(output, source);
console.log(`wrote ${output}`);
console.log(`model sha256 ${contentHash}`);

function canonicalTier1(entries: HeaderChoice[]): HeaderChoice[] {
  const fixed = ["com", "net", "org"];
  const byKey = new Map(entries.map((entry) => [`${entry.kind}:${entry.key}`, entry]));
  const ordered = fixed.map((key) => byKey.get(`suffix:${key}`));
  if (ordered.some((entry) => !entry)) {
    throw new Error("Every mode must retain the fixed com/net/org tier-one suffixes");
  }
  const fixedKeys = new Set(fixed.map((key) => `suffix:${key}`));
  return [...ordered as HeaderChoice[], ...entries.filter((entry) => !fixedKeys.has(`${entry.kind}:${entry.key}`))];
}

function encodeEntry(entry: HeaderChoice): string {
  if (!entry.key || entry.key.includes("\t")) throw new Error(`Invalid header entry: ${entry.key}`);
  return `${entry.kind === "host" ? "h" : "s"}:${entry.key}`;
}
