// Generated by scripts/write-trained-model.py from data/wiki/enwiki-analysis-sample.md.
// Full churn is expected between codec versions; do not preserve payload compatibility.

export const LITERAL_ALPHABET = "t/eoais.wrnphclm-dg0u:12bf=yvk_349&5867?%xA+jCSD";

export const PRIMARY_DICTIONARY = [
  "http://www.",
  "http://",
  ".com/",
  ".com",
  ".html",
  ".org/",
  ".org",
  "/news/",
  "/index.php/",
  "/search/",
  "/news",
] as const;

export const EXTENDED_DICTIONARY = [
  "/index.php",
  ".php",
  ".htm",
  ".uk/",
  "/search",
  "index.php",
  "/cgi-bin/",
  "/article/",
  "/cgi-bin",
  "/articles/",
  "search",
  "/article",
  "news",
  ".net/",
  ".aspx",
  "/articles",
  ".pdf",
  "/votecounter.cgi/",
  "cgi-bin",
  "?id=",
  "&id=",
  "article",
  "/index.html/",
  "/votecounter.cgi",
  ".edu/",
  "articles",
  "votecounter.cgi",
  "/index.html",
  "/askalibrarian/",
  ".gov/",
  "/books/",
  "/askalibrarian",
  ".net",
] as const;

export const DICTIONARY = [...PRIMARY_DICTIONARY, ...EXTENDED_DICTIONARY] as const;

export const ASCII_SYMBOL = LITERAL_ALPHABET.length + PRIMARY_DICTIONARY.length;
export const NUMBER_SYMBOL = ASCII_SYMBOL + 1;
export const REF_SYMBOL = NUMBER_SYMBOL + 1;
export const EXT_DICT_SYMBOL = REF_SYMBOL + 1;
export const END_SYMBOL = EXT_DICT_SYMBOL + 1;
export const SYMBOL_COUNT = END_SYMBOL + 1;

if (SYMBOL_COUNT > 64) {
  throw new Error(`Model has ${SYMBOL_COUNT} symbols; packed MVP supports at most 64`);
}

if (EXTENDED_DICTIONARY.length > 64) {
  throw new Error("Extended dictionary supports at most 64 entries in the MVP");
}

export const MIN_REF_LENGTH = 4;
export const MAX_REF_LENGTH = MIN_REF_LENGTH + 63;
export const MAX_REF_OFFSET = 4095;
export const MIN_NUMBER_LENGTH = 4;
export const MAX_NUMBER_LENGTH = 64;

export function literalSymbol(char: string): number | undefined {
  const index = LITERAL_ALPHABET.indexOf(char);
  return index === -1 ? undefined : index;
}

export function dictionarySymbol(id: number): number {
  if (id < PRIMARY_DICTIONARY.length) return LITERAL_ALPHABET.length + id;
  return EXT_DICT_SYMBOL;
}

export function primaryDictionaryValue(symbol: number): string | undefined {
  const index = symbol - LITERAL_ALPHABET.length;
  return index < 0 ? undefined : PRIMARY_DICTIONARY[index];
}

export function extendedDictionaryValue(index: number): string | undefined {
  return EXTENDED_DICTIONARY[index];
}

export function extendedDictionaryIndex(id: number): number {
  return id - PRIMARY_DICTIONARY.length;
}

export function isExtendedDictionaryId(id: number): boolean {
  return id >= PRIMARY_DICTIONARY.length;
}

export function decimalBitWidth(length: number): number {
  if (!Number.isInteger(length) || length < 1 || length > MAX_NUMBER_LENGTH) {
    throw new Error(`Invalid decimal length: ${length}`);
  }

  return Math.ceil(length * Math.log2(10));
}
