// Generated by scripts/write-trained-model.py from data/commoncrawl/CC-MAIN-2026-21/commoncrawl-full-rust-analysis-reservoir.md.
// Full churn is expected between codec versions; do not preserve payload compatibility.

export const LITERAL_ALPHABET = "eaot-ir/sncl.mwdpu%hg02b1kf8yv359476D=B_EzAjx&C?";

export const PRIMARY_DICTIONARY = [
  ".com/",
  "www.",
  "product",
  ".html",
  "robots.txt",
  ".org/",
  "category",
  "index.php",
  "search",
  "news",
  ".com",
] as const;

export const EXTENDED_DICTIONARY = [
  "page",
  "blog",
  ".de/",
  ".ru/",
  "article",
  "github.",
  "gitlab.",
  "bitbucket.",
  "/tree/",
  "/blob/",
  "/issues/",
  "/pull/",
  "/commit/",
  "/releases/",
  "/src/",
  "/docs/",
  "x.com/",
  "twitter.com/",
  "/status/",
  "/statuses/",
  ".net/",
  "content",
  "detail",
  "author",
  ".php",
  "collection",
  "catalog",
  "id=",
  "event",
  "view",
  "shop",
  "publication",
  "archive",
  ".jp/",
  "forum",
  "categories",
  "2026",
  "post",
  "2025",
  "/tag/",
  ".edu",
  ".fr/",
  "services",
  ".it/",
  ".pl/",
  ".br/",
  "video",
  "2024",
  "order=",
  "profile",
  "download",
  "produkt",
  "attachment",
  "type=",
  ".nl/",
  ".gov",
  "gallery",
  "portfolio",
  ".pdf",
  "utm_source=",
  "/uploads/",
  ".aspx",
  "/citationstylelanguage/",
  "2023",
  "item",
  "2022",
  ".cn/",
  ".cz/",
  "wiki",
  "noticias",
  ".au/",
  "?showComment=",
  ".info/",
  "&utm_medium=",
  ".htm",
  "&utm_campaign=",
  "login",
  "2021",
  ".es/",
  ".ca/",
  "2020",
  "sort=",
  "/en/",
  "/04/",
  "contact",
  "resources",
  ".xn--p1ai/",
  "default",
  ".ch/",
  ".ua/",
  "tags",
  "action=",
  ".eu/",
  "/10/",
  ".org",
  "redirect_to=",
  "projects",
  ".in/",
  "?submissionId=",
  "/03/",
  "mode=",
  "/handle/",
  "lang=",
  ".co.kr/",
  "/06/",
  "uncategorized",
  "/05/",
  ".vn/",
  ".ro/",
  "/12/",
  ".at/",
  ".be/",
  ".uk/",
  ".tw/",
  ".hu/",
  ".se/",
  ".co.il/",
  ".gr/",
  ".tr/",
  "/11/",
  "/01/",
  "/topic",
  "obituaries",
  ".co/",
  ".online/",
  ".id/",
  "comments",
  "/09/",
] as const;

export const SHARE_DICTIONARY = [
  "youtube.com/watch?v=",
  "youtu.be/",
  "m.youtube.com/watch?v=",
  "music.youtube.com/watch?v=",
  "soundcloud.com/",
  "open.spotify.com/",
  "spotify.link/",
  "podcasts.apple.com/",
  "music.apple.com/",
  "github.com/",
  "gist.github.com/",
  "gitlab.com/",
  "bitbucket.org/",
  "x.com/",
  "twitter.com/",
  "instagram.com/",
  "www.instagram.com/",
  "tiktok.com/",
  "www.tiktok.com/",
  "vm.tiktok.com/",
  "reddit.com/r/",
  "www.reddit.com/r/",
  "old.reddit.com/r/",
  "redd.it/",
  "bsky.app/profile/",
  "threads.net/",
  "www.threads.net/",
  "facebook.com/",
  "www.facebook.com/",
  "fb.watch/",
  "linkedin.com/",
  "www.linkedin.com/",
  "medium.com/",
  "substack.com/",
  "notion.so/",
  "docs.google.com/",
  "drive.google.com/",
  "maps.google.com/",
  "goo.gl/maps/",
  "dropbox.com/",
  "box.com/",
  "figma.com/",
  "canva.com/",
  "miro.com/",
  "slack.com/",
  "discord.com/",
  "discord.gg/",
  "twitch.tv/",
  "clips.twitch.tv/",
  "vimeo.com/",
  "dailymotion.com/",
  "imgur.com/",
  "i.imgur.com/",
  "flickr.com/",
  "pinterest.com/",
  "pin.it/",
  "amazon.com/",
  "amzn.to/",
  "ebay.com/",
  "etsy.com/",
  "producthunt.com/",
  "news.ycombinator.com/",
  "lobste.rs/",
  "stackoverflow.com/questions/",
  "stackexchange.com/questions/",
  "arxiv.org/abs/",
  "doi.org/",
  "wikipedia.org/wiki/",
  "en.wikipedia.org/wiki/",
  "developer.mozilla.org/",
  "docs.python.org/",
  "npmjs.com/package/",
  "crates.io/crates/",
  "pypi.org/project/",
  "rubygems.org/gems/",
  "huggingface.co/",
  "kaggle.com/",
  "observablehq.com/",
  "codesandbox.io/",
  "codepen.io/",
  "replit.com/",
  "vercel.app/",
  "netlify.app/",
  "workers.dev/",
] as const;

export const DICTIONARY = [...PRIMARY_DICTIONARY, ...EXTENDED_DICTIONARY] as const;

export const ASCII_SYMBOL = LITERAL_ALPHABET.length + PRIMARY_DICTIONARY.length;
export const NUMBER_SYMBOL = ASCII_SYMBOL + 1;
export const REF_SYMBOL = NUMBER_SYMBOL + 1;
export const EXT_DICT_SYMBOL = REF_SYMBOL + 1;
export const END_SYMBOL = EXT_DICT_SYMBOL + 1;
export const SYMBOL_COUNT = END_SYMBOL + 1;

if (SYMBOL_COUNT > 64) {
  throw new Error(`Model has ${SYMBOL_COUNT} symbols; packed MVP supports at most 64`);
}

export const EXTENDED_DICTIONARY_BITS = Math.max(1, Math.ceil(Math.log2(Math.max(1, EXTENDED_DICTIONARY.length))));

if (EXTENDED_DICTIONARY.length > 128) {
  throw new Error("Extended dictionary supports at most 128 entries in the MVP");
}

export const MIN_REF_LENGTH = 3;
export const MAX_REF_LENGTH = MIN_REF_LENGTH + 63;
export const MAX_REF_OFFSET = 4095;
export const REF_SMALL_OFFSET_BITS = 4;
export const REF_SMALL_LENGTH_BITS = 4;
export const REF_MEDIUM_OFFSET_BITS = 8;
export const REF_MEDIUM_LENGTH_BITS = 5;
export const REF_LARGE_OFFSET_BITS = 12;
export const REF_LARGE_LENGTH_BITS = 6;
export const MIN_NUMBER_LENGTH = 4;
export const MAX_NUMBER_LENGTH = 64;

export const NUMBER_DATE_CODE = 0;
export const NUMBER_DATETIME_CODE = 1;
export const NUMBER_U64_CODE = 2;
export const DATE_FORMAT_BITS = 2;
export const DATETIME_FORMAT_BITS = 2;
export const DATE_YEAR_BASE = 1970;
export const DATE_YEAR_BITS = 8;
export const DATE_MONTH_BITS = 4;
export const DATE_DAY_BITS = 5;
export const TIME_HOUR_BITS = 5;
export const TIME_MINUTE_BITS = 6;
export const TIME_SECOND_BITS = 6;
export const TIME_MILLISECOND_BITS = 10;
export const U64_BITS = 64;

export const ASCII_HEX_CODE = 0;
export const ASCII_UUID_CODE = 1;
export const ASCII_PERCENT_CODE = 2;
export const ASCII_BASE64URL_CODE = 3;
export const ASCII_LOWER_HYPHEN_CODE = 4;
export const ASCII_CJK_CODE = 5;
export const ASCII_UNICODE_CODE = 6;
export const ASCII_SHARE_DICTIONARY_CODE = 7;
export const ASCII_YOUTUBE_VIDEO_CODE = 8;
export const ASCII_STRUCTURED_LENGTH_BITS = 6;
export const UNICODE_CODE_UNIT_BITS = 16;
export const SHARE_DICTIONARY_BITS = Math.max(1, Math.ceil(Math.log2(Math.max(1, SHARE_DICTIONARY.length))));
export const YOUTUBE_VIDEO_ID_LENGTH = 11;
export const YOUTUBE_VIDEO_PREFIXES = [
  "youtube.com/watch?v=",
  "youtu.be/",
  "m.youtube.com/watch?v=",
  "music.youtube.com/watch?v=",
] as const;
export const YOUTUBE_VIDEO_PREFIX_BITS = Math.ceil(Math.log2(YOUTUBE_VIDEO_PREFIXES.length));
export const HEX_ALPHABET = "0123456789abcdef";
export const BASE64URL_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
export const LOWER_HYPHEN_ALPHABET = "abcdefghijklmnopqrstuvwxyz-";

export function literalSymbol(char: string): number | undefined {
  const index = LITERAL_ALPHABET.indexOf(char);
  return index === -1 ? undefined : index;
}

export function dictionarySymbol(id: number): number {
  if (id < PRIMARY_DICTIONARY.length) return LITERAL_ALPHABET.length + id;
  return EXT_DICT_SYMBOL;
}

export function primaryDictionaryValue(symbol: number): string | undefined {
  const index = symbol - LITERAL_ALPHABET.length;
  return index < 0 ? undefined : PRIMARY_DICTIONARY[index];
}

export function extendedDictionaryValue(index: number): string | undefined {
  return EXTENDED_DICTIONARY[index];
}

export function extendedDictionaryIndex(id: number): number {
  return id - PRIMARY_DICTIONARY.length;
}

export function isExtendedDictionaryId(id: number): boolean {
  return id >= PRIMARY_DICTIONARY.length;
}

export function shareDictionaryValue(index: number): string | undefined {
  return SHARE_DICTIONARY[index];
}

export function youtubeVideoPrefix(index: number): string | undefined {
  return YOUTUBE_VIDEO_PREFIXES[index];
}

export function decimalBitWidth(length: number): number {
  if (!Number.isInteger(length) || length < 1 || length > MAX_NUMBER_LENGTH) {
    throw new Error(`Invalid decimal length: ${length}`);
  }

  return Math.ceil(length * Math.log2(10));
}
